from nltk.corpus import stopwords
from fuzzywuzzy import fuzz
from collections import defaultdict

nltk_stop_words = stopwords.words()

initial_stop_words = [
    'brokerage',
    'corp',
    'corporate',
    'advisor',
    'commercial',
    'investment',
    'organization',
    'enterpises',
    'holding',
    'development',
    'management',
    'commercial',
    'realty',
    'real',
    'estate',
    'group',
    'properties',
    'company',
    'associates',
    'partners',
    'inc',
    'co',
    'services',
    'llc',
    'property',
]

def stop_word_generator(initial_stop_words, corpus, threshold_value=80):
    all_words = [word for sub_list in [item.split() for item in list(corpus)] for word in sub_list]
    stor_dict = defaultdict(list)
    
    for word in initial_stop_words:
        for curr_word in all_words:
            if fuzz.ratio(word, curr_word) > threshold_value:
                stor_dict[word].append(curr_word)
    return stor_dict.values()


company_name_conversions = {}

company_name_conversions_post = {
    'cbre' : 'cb richard ellis',
    'g&e' : 'grubb & ellis',
    'jll' : 'jones lang lasalle',
}


states = {
    'ak': 'alaska',
    'al': 'alabama',
    'ar': 'arkansas',
    'as': 'american samoa',
    'az': 'arizona',
    'ca': 'california',
    'co': 'colorado',
    'ct': 'connecticut',
    'dc': 'district of columbia',
    'de': 'delaware',
    'fl': 'florida',
    'ga': 'georgia',
    'gu': 'guam',
    'hi': 'hawaii',
    'ia': 'iowa',
    'id': 'idaho',
    'il': 'illinois',
    'in': 'indiana',
    'ks': 'kansas',
    'ky': 'kentucky',
    'la': 'louisiana',
    'ma': 'massachusetts',
    'md': 'maryland',
    'me': 'maine',
    'mi': 'michigan',
    'mn': 'minnesota',
    'mo': 'missouri',
    'mp': 'northern mariana islands',
    'ms': 'mississippi',
    'mt': 'montana',
    'na': 'national',
    'nc': 'north carolina',
    'nd': 'north dakota',
    'ne': 'nebraska',
    'nh': 'new hampshire',
    'nj': 'new jersey',
    'nm': 'new mexico',
    'nv': 'nevada',
    'ny': 'new york',
    'oh': 'ohio',
    'ok': 'oklahoma',
    'or': 'oregon',
    'pa': 'pennsylvania',
    'pr': 'puerto rico',
    'ri': 'rhode island',
    'sc': 'south carolina',
    'sd': 'south dakota',
    'tn': 'tennessee',
    'tx': 'texas',
    'ut': 'utah',
    'va': 'virginia',
    'vi': 'virgin islands',
    'vt': 'vermont',
    'wa': 'washington',
    'wi': 'wisconsin',
    'wv': 'west virginia',
    'wy': 'wyoming'
}

stop_words_states = states.keys() + states.values()

additional_stop_words = [
    'sco',
    'cor',
    'ico',
    'eco',
    'cox',
    'cos',
    'cou',
    'com',
    'col',
    'con',
    'esate',
    'sellstate',
    'estae',
    'esta',
    'estatr',
    'westgate',
    'strate',
    'estatel',
    'estat',
    'states',
    'estatte',
    'state',
    'estates',
    'espate',
    'advisory',
    'truadvisors',
    'tenadvisors',
    'advison',
    'adviser',
    'advisers',
    'advisors',
    'advisor',
    'advsors',
    'advisros',
    'adviors',
    'advistors',
    'asscoaites',
    'associaes',
    'assocaites',
    'associated',
    'asssciates',
    'associate',
    'asscociates',
    'associaties',
    'ssociates',
    'associators',
    'associat',
    'assocates',
    'asociates',
    'asssociates',
    'assoicates',
    'assciates',
    'association',
    'll',
    'invstment',
    'invetment',
    'investmen',
    'investments',
    'invesments',
    'investmenr',
    'investmt',
    'investment',
    'winc',
    'ic',
    'inco',
    'parthners',
    'parthers',
    'parners',
    'parnters',
    'partnership',
    'parters',
    'parnterns',
    'partnesr',
    'cresapartners',
    'partnerse',
    'partner',
    'parnteres',
    'pariners',
    'prtns',
    'partnerships',
    'managmenet',
    'management',
    'managememnt',
    'managemetn',
    'managemnt',
    'managment',
    'mangement',
    'manageme',
    'manangement',
    'gruop',
    'groupjo',
    'groups',
    'grou',
    'holdings',
    'holding',
    'development',
    'devolpment',
    'develop',
    'develoment',
    'streetdevelopment',
    'developer',
    'developers',
    'developments',
    'developmen',
    'compa',
    'compant',
    'codman',
    'compay',
    'kompany',
    'copmany',
    'comapny',
    'compan',
    'companie',
    'commericial',
    'commerc',
    'commercia',
    'commerical',
    'commuercial',
    'commerdal',
    'comermical',
    'cpmmercial',
    'commercail',
    'commcerial',
    'bannercommercial',
    'commercuak',
    'cammercial',
    'comercial',
    'commerciai',
    'cormmercial',
    'commercieal',
    'comemrcial',
    'cornmercial',
    'commmercial',
    'commerce',
    'cscommercial',
    'commerclal',
    'commecial',
    'sdcommercial',
    'terracommercial',
    'commercialbyron',
    'corp',
    'realtor',
    'realtec',
    'realry',
    'renault',
    'reaty',
    'reality',
    'realy',
    'ralty',
    'royalty',
    'erealty',
    'reatly',
    'realt',
    'realthy',
    'servi',
    'dervices',
    'srvcs',
    'service',
    'servicessd',
    'servies',
    'serices',
    'serivces',
    'serviced',
    'serviceslj',
    'sevices',
    'servcessd',
    'brokered',
    'broerage',
    'broker',
    'brokarege',
    'brokerage',
    'brokerge',
    'propereties',
    'propterties',
    'propreties',
    'proprties',
    'propertie',
    'propertries',
    'properti',
    'prperties',
    'properies',
    'lfmproperties',
    'propertoes',
    'medproperties',
    'properites',
    'enterpises',
    'enterprise',
    'enterprises',
    'organiztion',
    'organizaion',
    'organizatoin',
    'organzation',
    'organziation',
    'organizaiton',
    'organization',
    'organizationl',
    'proeprty',
    'propery',
    'propertie',
    'poperty',
    'propertoes',
    'properti',
    'propety',
    'roberty',
    'properites',
    'coporate',
    'corporex',
    'corporation',
    'corportation',
    'corportate',
    'incorporated',
    'corporat',
    'corporate',
]